TheTable/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^menu' ,include('menu.urls')),
    url(r'^order/',include('order.urls')),
    url(r'^home/',include('home.urls')),
    url(r'^event/', include('event.urls')),
    url(r'^book_a_table/', include('book_a_table.urls')),
]

urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT )
urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'
urlpatterns =[
    url('^$', views.index, name='home')
]

order/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from order import views

app_name = 'order'
urlpatterns = [
    url(r'^$', views.order, name='order'),
    url(r'details/$', views.order_details, name='order_details'),
    # url(r'^(?P<pk1>[0-9]+)/add_detail/(?P<pk2>[0-9]+)/order/$',
    #     views.add_order, name='add_detail'),
    url(r'^(?P<pk1>[0-9]+)/add_detail/(?P<pk2>[0-9]+)/order/$',
        views.add_order, name='add_detail'),
    url(r'^details/pick-up/$', views.pick_up, name='pick-up'),
    url(r'^details/home-delivery/$', views.home_delivery,
        name='home-delivery'),
    url(r'^(?P<pk>[0-9]+)/mail_order/$',
        views.mail_order, name='mail_order'),
    url(r'^order_confirmation/$', views.mail_order, name='order_confirm'),
    url(r'^pickup_confirmation/$', views.mail_order, name='pickup_confirm')
]

order/models.py
import datetime

from django.db import models


class PickUp(models.Model):
    name = models.CharField(max_length=50)
    contact = models.IntegerField(null=True)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.CharField(max_length=50, default='customer name')
    phone_number = models.IntegerField(null=True)
    user_email = models.EmailField(max_length=100, null=True)
    user_address = models.CharField(max_length=200, null=True)
    user_message = models.CharField(max_length=500, null=True)
    date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.user + " -> " + str(self.id)


class Dish(models.Model):
    order = models.ManyToManyField(Order)
    name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name

order/forms.py
from django import forms

from order.models import Order, PickUp


class HomeForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('user', 'phone_number', 'user_email', 'user_address',
                  'user_message',)


class PickUpForm(forms.ModelForm):
    class Meta:
        model = PickUp
        fields = ('name', 'contact', 'email')

order/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.apps import apps
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect

from order.models import Dish, Order
from menu.models import SubMenu
from order.forms import Order, HomeForm, PickUpForm
from validate_email import validate_email
from django.core.mail import EmailMessage


def order(request):
    menu_model = apps.get_model('menu.Menu')
    sub_menu_model = apps.get_model('menu.SubMenu')
    all_menu = menu_model.objects.all()
    all_sub_menu = sub_menu_model.objects.all()
    return render(request, 'order/order.html',
                  {'all_menu': all_menu, 'all_sub_menu': all_sub_menu})


def order_details(request):
    return render(request, 'order/order_details.html')


def add_order(request, pk1, pk2):
    # sub_menu_model = apps.get_model('menu.SubMenu')
    add_sub_menu = SubMenu.objects.get(pk=pk1)
    menu_model = apps.get_model('menu.Menu')
    sub_menu_model = apps.get_model('menu.SubMenu')

    all_menu = menu_model.objects.all()
    all_sub_menu = sub_menu_model.objects.all()
    dish_name = add_sub_menu.dish_name

    dish_price = add_sub_menu.price
    order_list = Order.objects.get(pk=pk2)

    dish = Dish.objects.create(name=dish_name, price=dish_price)
    dish.order.add(Order.objects.get(pk=pk2))
    dish.save()

    get_dishes = Dish.objects.all()
    final_dishes = ""

    value = ""
    sum = 0
    for i in get_dishes:
        print(order_list.id)
        print(pk2)

        try:
            value = i.order.get(pk=order_list.id)
            print(value)
            print('reached')
            if value is not None:
                final_dishes = Dish.objects.filter(
                    order=i.order.get(pk=order_list.id)).all()
                print(final_dishes)
                print(value.user_email)
                for i in final_dishes:
                    sum += i.price

                break
            else:
                continue
        except Exception as e:
            continue

    return render(request, 'order/order.html',
                  {'final_dishes': final_dishes, 'all_menu': all_menu,
                   'all_sub_menu': all_sub_menu, 'order_id': pk2,
                   'value': value, 'sum': sum})


@csrf_protect
def home_delivery(request):
    if request.method == 'POST':
        home_form = HomeForm(request.POST)

        if home_form.is_valid():
            homes = home_form.save(commit=False)
            homes.save()
            print(homes.id)
            menu_model = apps.get_model('menu.Menu')
            sub_menu_model = apps.get_model('menu.SubMenu')

            all_menu = menu_model.objects.all()
            all_sub_menu = sub_menu_model.objects.all()

            return render(request, 'order/order.html', {'all_menu': all_menu,
                                                        'all_sub_menu': all_sub_menu,
                                                        'order_id': homes.id})

        else:
            print(home_form.errors)

    else:
        home_form = HomeForm()

    return render(request, 'order/order_details.html',
                  {'home_form': home_form})


@csrf_protect
def pick_up(request):
    if request.method == 'POST':
        pick_form = PickUpForm(request.POST)

        if pick_form.is_valid():
            homes = pick_form.save(commit=False)
            # name = home_form.cleaned_data['name']
            # email = home_form.cleaned_data['email']
            homes.save()
            return render(request, 'order/pickup_confirmation.html', {})
        else:
            print(pick_form.errors)

    else:
        pick_form = PickUpForm()

    return render(request, 'order/order_details.html',
                  {'pick_form': pick_form})


def mail_order(request, pk):
    user = Order.objects.get(pk=pk)
    name = user.user
    email_send = user.user_email
    number = user.phone_number

    print (number)

    email = EmailMessage('Regarding Home Delivery',
                         "Received mail from " + str(
                             email_send) + "\n\n" + "name: " +
                         str(name) + "\n" + "contact: " + str(number),
                         to=['mahisaniyapayal@gmail.com', ])
    email.send()

    email = EmailMessage('Regarding Home Delivery',
                         "Hey " + str(
                             name) + ",\n\n" + "We have "
                                               "received "
                                               "your request "
                                               "for order "
                                               "\n" +
                         "We will contact you shortly on " + str(number),
                         to=[email_send,],
                         reply_to=[email_send, ])
    email.send()
    return render(request, 'order/pickup_confirmation.html')

order/templates/order/customer_registration.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
<br><br><br><br>
<form class="form-horizontal" action="" method="post"
      enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'book_a_table/form_registration.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

order/templates/order/form_registration.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <div class="text-danger small">{{ field.errors }}</div>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

order/templates/order/order.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% load staticfiles %}
{% block body %}

<section id="order">
  <div class="container">
    <div class="row" style="margin-top: 100px;">
      <div class="col-sm-2">
        <div class="ver-nav">
          <h3>CATEGORY</h3>
          <hr>
          <div class="categ">
            <ul class="nav nav-pills nav-stacked" style="margin-top: -20px;">
              {% for menu in all_menu %}
              <li><a data-toggle="pill"
                     href="#{{ menu.id }}"
                     style="text-transform: capitalize">
                {{ menu.category_name }}
              </a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-sm-7">

        <h2>OUR MENU</h2>
        <p>We present you our range of hot and sizzling dishes by our
          chefs.</p>
              <!-- <div class="col-md-8"> -->
                  <div class="sub-menu-card"
                       style="background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuwWlIFyn_dpmRk7zNRFk5wpXAMlpN_JOiuWBhbKzPdYQ5Dce1JA');">
                    <div class="tab-content">
                      {% for menu in all_menu %}
                      <div id="{{ menu.id }}"
                           class="tab-pane fade in {% if menu.id == 1 %}active{% else %} {% endif %}">
                        <div class="table-flexible">
                          <table class="table borderless">
                            <tbody>
                            <tr>
                              <td colspan="3" class="text-center">
                                <span class="secTitle"
                                      style="text-transform: capitalize">{{ menu.category_name }} </span>
                              </td>
                            </tr>
                            {% for submenu in all_sub_menu %}
                            {% if submenu.menu == menu %}
                            <tr>
                              <td>
                                <div class="dishName"
                                      style="text-transform: capitalize; ">{{ submenu.dish_name }}</div>
                              </td>
                              <td class="price">&#8377;{{ submenu.price }}</td>
                              <td>
                                <a
                                  href="{% url 'order:add_detail' submenu.id order_id %}"
                                  style="color: #3c763d"><i
                                  class="fa fa-plus" aria-hidden="true"></i></a>
                              </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                            </tbody>
                          </table>
                        </div>
                      </div>
                      {% endfor %}
                    </div>
                  </div>

      </div>
      <div class="col-sm-3">
        <div class="myOrder">
          <h3>MY ORDER</h3>
          <hr>
          <div class="row">
            <div class="cart">
              {% if final_dishes is not None %}
              {% for list in final_dishes %}
              <h5>1 &times;
                &emsp13;&emsp13;{{ list.name}}&emsp13;&#8377;{{list.price}} </h5>
              {% endfor %}
              {% endif %}
            </div>
            <!-- {{order_id}} -->
            <div class="total">
              <hr style="margin: 0 30px;">
              <h4>Sub Total: {{ sum }}</h4>
            </div>
            <form action="" method="Post">
              {% csrf_token %}
              <button type="submit" class="btn  btn-lg"
                    style="margin: 10px 40px; padding: 7px 40px;">
                    <!-- {{order_id}} -->
                <a href="{% url 'order:mail_order' order_id %}">Order Now</a>
            </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

order/templates/order/order_confirmation.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% load staticfiles %}
{% block body %}
<section id="image-back" class="no-margin"
         xmlns="http://www.w3.org/1999/html"
         xmlns="http://www.w3.org/1999/html">
  <div class="row" style="margin: auto;">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <img src="{% static 'img/back1.jpg' %}"/>
    </div>
    <div class="col-md-1"></div>
  </div>


</section>

<section id="order">
  <div class="container">
    <div class="row">
      <div class="col-md-2">

      </div>
      <div class="col-md-8">

        <h2>Order Confirmation</h2>
        <p>You will recieve a confirmation mail shortly</p>
      </div>
      <div class="col-md-2">
      </div>
    </div>
  </div>
</section>
{% endblock %}

order/templates/order/order_details.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% load staticfiles %}
{% block body %}
<section id="image-back" class="no-margin"
         xmlns="http://www.w3.org/1999/html"
         xmlns="http://www.w3.org/1999/html">

  <div class="row" style="margin: auto;">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <img src="{% static 'img/back1.jpg' %}"/>
    </div>
    <div class="col-md-1"></div>
  </div>

</section>
<section id="order">
  <div class="container">
    <div class="row" style="margin-top:80px;">
      <div class="col-md-2"></div>
      <div class="col-sm-8" style="margin-top: 2%;">
        <div class="order-type">
          <!-- <ul class="nav nav-tabs">
            <li><a data-toggle="tab" href="#homeDelivery" class="active">Home
              Delivery</a>
            </li>
            <!-- <li><a data-toggle="tab" href="#pickUp">Pick
              Up</a></li>

          </ul> -->

          <div class="tab-content">
            <!-- <div id="pickUp" class="tab-pane fade in">
              <h2>PICK UP</h2>
              <h4>Order online or call us on 079-23223440 between 10:00AM -
                9:00PM.</h4>
              <h4> We will send you confirmation as soon as we can.</h4>
              <h4><b>Opening Hours:</b></h4>
              <h4>Lunch : 11:00 AM - 3:30 PM</h4>
              <h4>Dinner : 6:30 AM - 10:30 PM</h4>
              <br><br>
              <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                  <form class="form-horizontal login-form"
                        action="{% url 'order:pick-up' %}"
                          method="post">
                    {% csrf_token %}
                    <div class="form-group relative">
                      <input id="{{ pick_form.name1 }}" name="name"
                             class="form-control input"
                               type="text"
                               placeholder="Name" required>
                      <i class="fa fa-user"></i>
                    </div>
                    <div class="form-group relative">
                        <input id="{{ pick_form.contact1 }}" name="contact"
                               class="form-control input" type="tel"
                               placeholder="Contact" required>
                      <i class="fa fa-phone"></i>
                    </div>
                    <div class="form-group relative">
                      <input id="{{ pick_form.email1 }}" name="email"
                             class="form-control input" type="email"
                             placeholder="Email" required>
                      <i class="fa fa-envelope"></i>
                    </div>
                    <div class="form-group">

                      <input type="submit" value="Send" id="submit"
                             class="btn btn-green btn-lg btn-block">
                    </div>
                  </form>
                </div>
                <div class="col-sm-1"></div>
              </div> -->
            </div>
            <div id="homeDelivery" class="tab-pane fade in active">
              <h2>HOME DELIVERY</h2>
              <h4>Order online or call us on 079-23223440 between 10:00AM -
                9:00PM.</h4>
              <h4> We will send you confirmation as soon as we can.</h4>
              <br><br>
              <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                  <form class="form-horizontal login-form"
                        action="{% url 'order:home-delivery' %}"
                          method="post">
                    {% csrf_token %}
                    <div class="form-group relative">
                      <input id="{{ home_form.user1 }}" name="user"
                             class="form-control input"
                             type="text"
                             placeholder="Name" required>
                      <i class="fa fa-user"></i>
                    </div>
                    <div class="form-group relative">
                      <input id="{{ home_form.phone_number1 }}"
                             name="phone_number"
                             class="form-control input" type="tel"
                             placeholder="Contact" required>
                      <i class="fa fa-phone"></i>
                    </div>
                    <div class="form-group relative">
                      <input id="{{ home_form.user_email1 }}" name="user_email"
                             class="form-control input" type="email"
                             placeholder="Email" required>
                      <i class="fa fa-envelope"></i>
                    </div>
                    <div class="form-group relative">
                      <input id="{{ home_form.user_address1 }}"
                             name="user_address"
                             class="form-control input" type="text"
                             placeholder="Address" required>
                      <i class="fa fa-map-marker"></i>
                    </div>
                    <div class="form-group relative">
                      <input id="{{ home_form.user_message1 }}"
                             name="user_message"
                             class="form-control input" type="text"
                             placeholder="Message" required>
                      <i class="fa fa-microphone"></i>
                    </div>
                    <div class="form-group">
                      <input type="submit" value="Send"
                             class="btn btn-green btn-lg btn-block">
                    </div>
                  </form>
                </div>
                <div class="col-sm-1"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-2"></div>
    </div>
  </div>
</section>
{% endblock %}

order/templates/order/pickup_confirmation.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% load staticfiles %}
{% block body %}
<section id="image-back" class="no-margin"
         xmlns="http://www.w3.org/1999/html"
         xmlns="http://www.w3.org/1999/html">
  <div class="row" style="margin: auto;">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <img src="{% static 'img/back1.jpg' %}"/>
    </div>
    <div class="col-md-1"></div>
  </div>


</section>

<section id="order">
  <div class="container">
    <div class="row" style="margin-top: 80px; height: 300px;">
      <div class="col-md-2">

      </div>
      <div class="col-md-8">

        <h2>Order Confirmation</h2>
        <p>You will recieve a confirmation mail shortly</p>
      </div>
      <div class="col-md-2">
      </div>
    </div>
  </div>
</section>
{% endblock %}