TheTable/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^menu' ,include('menu.urls')),
    url(r'^order/',include('order.urls')),
    url(r'^home/',include('home.urls')),
    url(r'^event/', include('event.urls')),
    url(r'^book_a_table/', include('book_a_table.urls')),
]

urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT )
urlpatterns += staticfiles_urlpatterns()

book_a_table/urls.py
from book_a_table import views
from django.conf.urls import url

app_name = 'book_a_table'

urlpatterns = [
    url(r'^$', views.book_table, name='book'),
]

event/urls.py
from django.conf.urls import url
from event import views

app_name="event"
urlpatterns=[
    url('^$', views.events , name='event')
]

home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'
urlpatterns =[
    url('^$', views.index, name='home')
]

menu/urls.py
from django.conf.urls import url
from menu import views
app_name ='menu'
urlpatterns=[
    #url(r'^$',views.menu, name='menu'),

    url(r'^$',views.sub_menu , name='menu')
]

order/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from order import views

app_name = 'order'
urlpatterns = [
    url(r'^$', views.order, name='order'),
    url(r'details/$', views.order_details, name='order_details'),
    # url(r'^(?P<pk1>[0-9]+)/add_detail/(?P<pk2>[0-9]+)/order/$',
    #     views.add_order, name='add_detail'),
    url(r'^(?P<pk1>[0-9]+)/add_detail/(?P<pk2>[0-9]+)/order/$',
        views.add_order, name='add_detail'),
    url(r'^details/pick-up/$', views.pick_up, name='pick-up'),
    url(r'^details/home-delivery/$', views.home_delivery,
        name='home-delivery'),
    url(r'^(?P<pk>[0-9]+)/mail_order/$',
        views.mail_order, name='mail_order'),
    url(r'^order_confirmation/$', views.mail_order, name='order_confirm'),
    url(r'^pickup_confirmation/$', views.mail_order, name='pickup_confirm')
]

templates/base.html
<html lang="en">
<head>
    {% block title %}
    <title>TheTable Restaurant</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Allura' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Actor' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Abril Fatface' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Angkor' rel='stylesheet'>

    <style>
  /*  header navbar */
        .navbar-custom{
            padding-top:7px !important;
            padding-bottom:7px !important;
        }
        .top-nav .navbar-custom{

        	margin: 0px 0px;
        	background-color: #FFF;
        }
        .navbar-nav li i {
        	color:#f36700;
        }
  /* header navbar*/

/* footer */
.context-dark, .bg-gray-dark, .bg-primary {
    color: rgba(255, 255, 255, 0.8);
}

.footer-classic a, .footer-classic a:focus, .footer-classic a:active {
    color: #ffffff;
}
.nav-list li {
    padding-top: 5px;
    padding-bottom: 5px;
}

.nav-list li a:hover:before {
    margin-left: 0;
    opacity: 1;
    visibility: visible;
}

ul, ol {
    list-style: none;
    padding: 0;
    margin: 0;
}

.social-inner {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    padding: 23px;
    font: 900 13px/1 "Lato", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    text-transform: uppercase;
    color: rgba(255, 255, 255, 0.5);
}
.social-container .col {
    border: 1px solid rgba(255, 255, 255, 0.1);
}
.nav-list li a:before {
    content: "\f14f";
    font: 400 21px/1 "Material Design Icons";
    color: #4d6de6;
    display: inline-block;
    vertical-align: baseline;
    margin-left: -28px;
    margin-right: 7px;
    opacity: 0;
    visibility: hidden;
    transition: .22s ease;
}
/* footer */
  </style>
</head>

<body>
      <div class="top-nav">
        <nav class="navbar navbar-default  navbar-fixed-top navbar-custom navbar">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/The_Table_%28restaurant%29_logo.png/1200px-The_Table_%28restaurant%29_logo.png" width="80px" height="35px"></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav">
                  <li ><a href="{% url 'home:home' %}">Home</a></li>
                  <li><a href="{% url 'home:home' %}#about-us">About</a></li>
                  <li><a href="{% url 'menu:menu' %}">Menu</a></li>
                  <li><a href="{% url 'order:order_details' %}">Order</a></li>
                  <li><a href="{% url 'book_a_table:book' %}">Reservation</a></li>
                  <!--<li><a href="#gallery">Gallery</a></li>-->
                  <li><a href="{% url 'event:event' %}">Events</a></li>
                  <li><a href="#">Contact</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><i class="fa fa-phone"></i> 91-7568543012</a></li>
                <li><a href="#"><i class="fa fa-map-marker"></i> Gandhinagar sector 16</a></li>
              </ul>
            </div>
          </div>
        </nav>
    </div>


{% block body %}
{% endblock %}

<br>

      <div class="footer section  footer-classic context-dark" style="background: #2d3246; ">
          <div class="container">
              <div class="row row-30">
                  <div class="col-sm-4 col-xl-5">
                      <div class="pr-xl-4">
                        <p style="margin-top: 10px;">TheTable Restaurant is a place for simplicity. Good food, good beer, and good service.</p>

                        <p class="rights"><span>©  </span><span class="copyright-year">2018</span><span></span><span>TheTable Restarurant.</span></p>
                      </div>
                      <i style="font-size:24px" class="fa"><a href="#">&#xf09a;</a></i> &nbsp; &nbsp; &nbsp;
                      <i style="font-size:24px" class="fa"><a href="#">&#xf16d;</a></i> &nbsp; &nbsp; &nbsp;
                      <i style="font-size:24px" class="fa"><a href="#">&#xf099;</a></i> &nbsp; &nbsp; &nbsp;
                      <i style="font-size:24px" class="fa"><a href="#">&#xf1a0;</a></i>
                  </div>
                  <div class="col-sm-4">
                     <div style="margin-left: 100px; ">
                          <h4>Contacts</h4>
                          <dl class="contact-list">
                            <dt>Address:</dt>
                            <dd>1st Floor Near Gandhinagar Nagrik Bank GH-4II, Sector-16, Gandhinagar</dd>
                          </dl>
                          <dl class="contact-list">
                            <dt>email:</dt>
                            <dd><a href="mailto:#">thetableresto@gmail.com</a></dd>
                          </dl>

                          <dl class="contact-list">
                            <dt>phones:</dt>
                            <dd><a href="tel:#">+91 7568543012</a> <span>or</span> <a href="tel:#">+91 9571195353</a>
                            </dd>
                          </dl>
                       </div>
                  </div>
                  <div class="col-sm-4" >
                     <div style="margin-left: 100px; ">
                        <h5>Links</h5>
                        <ul class="nav-list">
                          <li ><a href="{% url 'home:home' %}">Home</a></li>
                          <li><a href="{% url 'home:home' %}#about-us">About</a></li>
                          <li><a href="{% url 'menu:menu' %}">Menu</a></li>
                          <li><a href="#order">Order</a></li>
                          <li><a href="{% url 'book_a_table:book' %}">Reservation</a></li>
                          <!--<li><a href="#gallery">Gallery</a></li>-->
                          <li><a href="{% url 'event:event' %}">Events</a></li>

                        </ul>
                      </div>
                  </div>
                </div>
            </div>
       </div>
    </body>
</html>

templates/form_template.html
{% for field in form %}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <div class="text-danger small">{{ field.errors }}</div>
  </div>
  <label class="control-label col-sm-2">{{ field.label_tag }}</label>
  <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

templates/generic_form.html
{#{% extends 'base.html' %}#}
{#{% block title %} Register {% endblock %}#}
{#{% block body %}#}
<form class="form-horizontal" action="" method="post"
      enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'form_template.html' %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-success">Submit</button>
    </div>
  </div>
</form>
{#{% endblock %}#}